# Autogenerated wrapper script for PCRE2_jll for aarch64-apple-darwin
export libpcre2_16, libpcre2_32, libpcre2_8

JLLWrappers.@generate_wrapper_header("PCRE2")
JLLWrappers.@declare_library_product(libpcre2_16, "@rpath/libpcre2-16.0.dylib")
JLLWrappers.@declare_library_product(libpcre2_32, "@rpath/libpcre2-32.0.dylib")
JLLWrappers.@declare_library_product(libpcre2_8, "@rpath/libpcre2-8.0.dylib")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libpcre2_16,
        "lib/libpcre2-16.0.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libpcre2_32,
        "lib/libpcre2-32.0.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libpcre2_8,
        "lib/libpcre2-8.0.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
