# Autogenerated wrapper script for PCRE2_jll for i686-w64-mingw32
export libpcre2_8, libpcre2_32, libpcre2_16

## Global variables
PATH = ""
LIBPATH = ""
LIBPATH_env = "PATH"

# Relative path to `libpcre2_8`
const libpcre2_8_splitpath = ["bin", "libpcre2-8-0.dll"]

# This will be filled out by __init__() for all products, as it must be done at runtime
libpcre2_8_path = ""

# libpcre2_8-specific global declaration
# This will be filled out by __init__()
libpcre2_8_handle = C_NULL

# This must be `const` so that we can use it with `ccall()`
const libpcre2_8 = "libpcre2-8-0.dll"


# Relative path to `libpcre2_32`
const libpcre2_32_splitpath = ["bin", "libpcre2-32-0.dll"]

# This will be filled out by __init__() for all products, as it must be done at runtime
libpcre2_32_path = ""

# libpcre2_32-specific global declaration
# This will be filled out by __init__()
libpcre2_32_handle = C_NULL

# This must be `const` so that we can use it with `ccall()`
const libpcre2_32 = "libpcre2-32-0.dll"


# Relative path to `libpcre2_16`
const libpcre2_16_splitpath = ["bin", "libpcre2-16-0.dll"]

# This will be filled out by __init__() for all products, as it must be done at runtime
libpcre2_16_path = ""

# libpcre2_16-specific global declaration
# This will be filled out by __init__()
libpcre2_16_handle = C_NULL

# This must be `const` so that we can use it with `ccall()`
const libpcre2_16 = "libpcre2-16-0.dll"


"""
Open all libraries
"""
function __init__()
    global artifact_dir = abspath(artifact"PCRE2")

    # Initialize PATH and LIBPATH environment variable listings
    global PATH_list, LIBPATH_list
    # We first need to add to LIBPATH_list the libraries provided by Julia
    append!(LIBPATH_list, [Sys.BINDIR, joinpath(Sys.BINDIR, Base.LIBDIR, "julia"), joinpath(Sys.BINDIR, Base.LIBDIR)])
    global libpcre2_8_path = normpath(joinpath(artifact_dir, libpcre2_8_splitpath...))

    # Manually `dlopen()` this right now so that future invocations
    # of `ccall` with its `SONAME` will find this path immediately.
    global libpcre2_8_handle = dlopen(libpcre2_8_path)
    push!(LIBPATH_list, dirname(libpcre2_8_path))

    global libpcre2_32_path = normpath(joinpath(artifact_dir, libpcre2_32_splitpath...))

    # Manually `dlopen()` this right now so that future invocations
    # of `ccall` with its `SONAME` will find this path immediately.
    global libpcre2_32_handle = dlopen(libpcre2_32_path)
    push!(LIBPATH_list, dirname(libpcre2_32_path))

    global libpcre2_16_path = normpath(joinpath(artifact_dir, libpcre2_16_splitpath...))

    # Manually `dlopen()` this right now so that future invocations
    # of `ccall` with its `SONAME` will find this path immediately.
    global libpcre2_16_handle = dlopen(libpcre2_16_path)
    push!(LIBPATH_list, dirname(libpcre2_16_path))

    # Filter out duplicate and empty entries in our PATH and LIBPATH entries
    filter!(!isempty, unique!(PATH_list))
    filter!(!isempty, unique!(LIBPATH_list))
    global PATH = join(PATH_list, ';')
    global LIBPATH = join(LIBPATH_list, ';')

    # Add each element of LIBPATH to our DL_LOAD_PATH (necessary on platforms
    # that don't honor our "already opened" trick)
    #for lp in LIBPATH_list
    #    push!(DL_LOAD_PATH, lp)
    #end
end  # __init__()

